from app.models import Engineer, Incident

INCIDENTS = [
    Incident(
        id="INC001",
        title="Payment service latency high",
        severity="HIGH",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T10:00:00Z",
    ),
    Incident(
        id="INC002",
        title="Email notification delay",
        severity="MEDIUM",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T11:00:00Z",
    ),
    Incident(
        id="INC003",
        title="Order creation API returning 500",
        severity="HIGH",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T11:30:00Z",
    ),
    Incident(
        id="INC004",
        title="User login failures increased",
        severity="HIGH",
        status="ACKNOWLEDGED",
        assigned_to="Priya",
        notes=["Initial investigation started"],
        created_at="2026-04-23T12:00:00Z",
    ),
    Incident(
        id="INC005",
        title="Inventory sync delay",
        severity="MEDIUM",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T12:30:00Z",
    ),
    Incident(
        id="INC006",
        title="Notification worker queue backlog",
        severity="LOW",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T13:00:00Z",
    ),
    Incident(
        id="INC007",
        title="Database CPU usage above threshold",
        severity="HIGH",
        status="ACKNOWLEDGED",
        assigned_to="Rahul",
        notes=["DB metrics checked", "Possible slow query detected"],
        created_at="2026-04-23T13:30:00Z",
    ),
    Incident(
        id="INC008",
        title="Search service response time degraded",
        severity="MEDIUM",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T14:00:00Z",
    ),
    Incident(
        id="INC009",
        title="Cache miss rate unusually high",
        severity="LOW",
        status="RESOLVED",
        assigned_to="Aman",
        notes=["Cache configuration refreshed", "Issue resolved"],
        created_at="2026-04-23T14:30:00Z",
    ),
    Incident(
        id="INC010",
        title="Checkout page timeout reported",
        severity="HIGH",
        status="OPEN",
        assigned_to=None,
        notes=[],
        created_at="2026-04-23T15:00:00Z",
    ),
]

ENGINEERS = [
    Engineer(id="ENG001", name="Rahul", is_on_call=True),
    Engineer(id="ENG002", name="Aman", is_on_call=False),
    Engineer(id="ENG003", name="Priya", is_on_call=True),
    Engineer(id="ENG004", name="Sneha", is_on_call=False),
    Engineer(id="ENG005", name="Karan", is_on_call=True),
    Engineer(id="ENG006", name="Neha", is_on_call=False),
]